Repository sysec-uic/AutoPatch-LLM, pull requests merged in 2025-03, with the labels that each got.

#26 doc: Add FuzzBench doc
  docs/TechnicalSpikes/002.oss-fuzz-techincal-spike.md
Labels: documentation

#43 feature(releases): Add first pre-release GHA for tracking latest tag to main branch
  .devcontainer/devcontainer.json
  .github/workflows/pre-release.yml
  Taskfile.yml
  src/autopatchdatatypes/Taskfile.yml
Labels: enhancement

#44 add automated tests for crashdetail datatype
  src/autopatchdatatypes/autopatchdatatypes/test_crash_detail.py
Labels: enhancement

#49 release(v0.2.0): fix invocation of package install in root task for CI
  .github/workflows/release.yml
Labels: bug

#50 release(v0.2.2): Align first draft release pipeline with test pipeline
  .github/workflows/release.yml
Labels: bug

#51 release(v0.2.3): Correctly sparse clone the input codebase for automa…
  .github/workflows/release.yml
  pyproject.toml
  src/autopatchdatatypes/pyproject.toml
  src/autopatchpubsub/pyproject.toml
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/pyproject.toml
  src/fuzzing-service/requirements.txt
Labels: bug

#45 Add Github CODEOWNERS file
  .github/CODEOWNERS
Labels: documentation, enhancement

#61 bugfix(dockernetwork): add network as code and automation for indempo…
  .devcontainer/devcontainer.json
  Taskfile.yml
  assets/create-docker-network.py
Labels: bug

#63 hotfix(pre-release): remove autopatchpubsub build and install step from dev build as that component is still in Code Review
  Taskfile.yml
Labels: bug

#64 hotfix/pre release ci
  Taskfile.yml
Labels: bug

#68 release(v0.3.0): re-add correct test config files for CI
  .github/workflows/release.yml
Labels: enhancement

#58 Docs/oss fuzz tech spike adr
  .gitignore
  docs/TechnicalSpikes/002.fuzz-bench-techincal-spike.md
  docs/TechnicalSpikes/003.oss-fuzz-technical-spike.md
  docs/images/build_libxml_fuzzer_with_local_chcekout.png
  docs/images/result_of_libxml2_no_reproduce_wrong_commit.png
  docs/images/results_of_libxml2_reproduction_on_buggy_checkout1_xml_abort.png
Labels: documentation

#73 config: use dataclass config type instead of raw dict in fuzz component
  .github/workflows/test-coverage.yml
  .gitignore
  src/archive_Dockerfile
  src/autopatchdatatypes/pyproject.toml
  src/autopatchpubsub/autopatchpubsub/message_broker_client.py
  src/autopatchpubsub/pyproject.toml
  src/autopatchshared/autopatchshared/__init__.py
  src/autopatchshared/autopatchshared/load_config_from_json.py
  src/autopatchshared/autopatchshared/test_load_config_as_json.py
  src/autopatchshared/pyproject.toml
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/config/config.json
  src/fuzzing-service/config/dev-config.json
  src/fuzzing-service/fuzz_svc_config.py
  src/fuzzing-service/fuzzing_service.py
  src/fuzzing-service/pyproject.toml
  src/fuzzing-service/requirements.txt
  src/fuzzing-service/tests/devcontainer-test-config.json
  src/fuzzing-service/tests/pytest.ini
  src/fuzzing-service/tests/test_fuzzing_service.py
Labels: bug, enhancement

#77 bugfix(devcontainer): remove env file from devontainer initial start up so devs have to opt in to use it instead of by default
  .devcontainer/devcontainer.env.example
  .devcontainer/devcontainer.json
Labels: bug

#79 Technical Spike docs/aflplusplus
  README.md
  docs/TechnicalSpikes/004.afl2.52b-to-afl++-technical-spike.md
  docs/images/image-1.png
  docs/images/image-10.png
  docs/images/image-2.png
  docs/images/image-3.png
  docs/images/image-4.png
  docs/images/image-5.png
  docs/images/image-7.png
  docs/images/image-8.png
  docs/images/image-9.png
  docs/images/image.png
Labels: documentation

#80 Docs/adr afl migration
  docs/ArchitecturalDecisionRecords/006.adr-afl2.52b-to-aflplusplus.md
  docs/TechnicalSpikes/004.afl2.52b-to-afl++-technical-spike.md
Labels: Architectural Decision Record

#86 feature(devtools-joern): add jeorn to development container
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: enhancement, Task
