Repository sysec-uic/AutoPatch-LLM, pull requests merged in 2025-04, with the labels that each got.

#90 docs(root readme): update high level system diagram
  README.md
  docs/Diagrams/autopatch-v.0.5.0.drawio.png
  docs/images/NSF-CAHSI-logo.png
  docs/images/google-logo.png
  pyproject.toml
  src/fuzzing-service/Taskfile.yml
  src/patch-evaluation-service/Taskfile.yml
Labels: documentation

#89 docs(technical-spike): simple technical spike looking at meta infer
  docs/TechnicalSpikes/005.meta-infer.md
Labels: documentation

#91 docs/references
  docs/References/references.bib
Labels: documentation

#97 feature(fuzzing-service): use layered docker builds for fuzzing service
  src/fuzzing-service/Dockerfile
Labels: enhancement

#96 feature(cpg generator): use layered builds for cpg generator
  docker-compose.yml
  src/code-property-graph-generator/Dockerfile
  src/code-property-graph-generator/README.md
  src/code-property-graph-generator/code_property_graph_generator.py
  src/code-property-graph-generator/test_code_property_graph_generator.py
Labels: enhancement

#98 layered builds for patch eval container
  src/patch-evaluation-service/Dockerfile
Labels: enhancement

#85 PR#1 new component llm-dispatch-service
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/test-coverage.yml
  .vscode/launch.json
  README.md
  Taskfile.yml
  docker-compose.yml
  src/autopatchdatatypes/autopatchdatatypes/__init__.py
  src/autopatchpubsub/autopatchpubsub/message_broker_client.py
  src/code-property-graph-generator/Dockerfile
  src/fuzzing-service/fuzzing_service.py
  src/fuzzing-service/tests/__init__.py
  src/fuzzing-service/tests/test_fuzzing_service.py
  src/llm-dispatch/.env.example
  src/llm-dispatch/Dockerfile
  src/llm-dispatch/README.md
  src/llm-dispatch/Taskfile.yml
  src/llm-dispatch/__init__.py
  src/llm-dispatch/config/config.json
  src/llm-dispatch/config/dev-config.json
  src/llm-dispatch/config/dev-logging-config.json
  src/llm-dispatch/config/logging-config.json
  src/llm-dispatch/data/dummy_c_file.c
  src/llm-dispatch/data/prompts/system_prompt.txt
  src/llm-dispatch/data/prompts/user_prompt.txt
  src/llm-dispatch/invoke-chatgpt-API-hello-world-2.py
  src/llm-dispatch/invoke-chatgpt-API-hello-world.py
  src/llm-dispatch/llm_dispatch.py
  src/llm-dispatch/llm_dispatch_config.py
  src/llm-dispatch/pyproject.toml
  src/llm-dispatch/pytest.ini
  src/llm-dispatch/requirements.txt
Labels: enhancement

#100 tests/llm dispatch service
  .vscode/launch.json
  Taskfile.yml
  docker-compose.yml
  src/fuzzing-service/tests/test_fuzzing_service.py
  src/llm-dispatch-service/.env.example
  src/llm-dispatch-service/Dockerfile
  src/llm-dispatch-service/README.md
  src/llm-dispatch-service/Taskfile.yml
  src/llm-dispatch-service/__init__.py
  src/llm-dispatch-service/config/config.json
  src/llm-dispatch-service/config/dev-config.json
  src/llm-dispatch-service/config/dev-logging-config.json
  src/llm-dispatch-service/config/logging-config.json
  src/llm-dispatch-service/data/dummy_c_file.c
  src/llm-dispatch-service/data/prompts/system_prompt.txt
  src/llm-dispatch-service/data/prompts/user_prompt.txt
  src/llm-dispatch-service/llm_dispatch_svc.py
  src/llm-dispatch-service/llm_dispatch_svc_config.py
  src/llm-dispatch-service/pyproject.toml
  src/llm-dispatch-service/pytest.ini
  src/llm-dispatch-service/requirements.txt
  src/llm-dispatch-service/test_llm_dispatch_service.py
  src/llm-dispatch/.env.example
  src/llm-dispatch/Taskfile.yml
Labels: enhancement

#101 prototype(cpg-notebooks): add code property graph generatr early rese…
  assets/notebooks/CPGdemo.ipynb
  assets/notebooks/run_joern-scan_results.ipynb
Labels: documentation

#102 Feature/docker container releases
  .github/workflows/build-and-push-docker-images.yml
Labels: enhancement

#105 should ignore ipynb from repo stats
  .gitattributes
Labels: documentation, enhancement

#107 Use software-properties-common v0.99.48
  .devcontainer/Dockerfile
Labels: bug

#104 release(v0.6.1-alpha): first revision llm dispatch component, docker container releases
  pyproject.toml
  src/autopatchdatatypes/pyproject.toml
  src/autopatchpubsub/pyproject.toml
  src/autopatchshared/pyproject.toml
  src/code-property-graph-generator/Dockerfile
  src/code-property-graph-generator/config/config.json
  src/code-property-graph-generator/config/dev-config.json
  src/code-property-graph-generator/pyproject.toml
  src/code-property-graph-generator/requirements.txt
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/config/config.json
  src/fuzzing-service/config/dev-config.json
  src/fuzzing-service/pyproject.toml
  src/fuzzing-service/requirements.txt
  src/llm-dispatch-service/Dockerfile
  src/llm-dispatch-service/config/config.json
  src/llm-dispatch-service/config/dev-config.json
  src/llm-dispatch-service/pyproject.toml
  src/llm-dispatch-service/requirements.txt
  src/patch-evaluation-service/Dockerfile
  src/patch-evaluation-service/config/config.json
  src/patch-evaluation-service/config/dev-config.json
  src/patch-evaluation-service/pyproject.toml
  src/patch-evaluation-service/requirements.txt
Labels: enhancement

#109 docs(system-diagram): update high level system diagram, add devtools …
  README.md
  docs/Diagrams/autopatch-devtools-v.0.6.1.drawio.png
  docs/Diagrams/autopatch-v.0.5.0.drawio.png
  docs/Diagrams/autopatch-v.0.5.1.drawio.png
  docs/Diagrams/autopatch-v.0.6.1.drawio.png
Labels: documentation

#111 bugfix typo in config var name
  src/llm-dispatch-service/config/config.json
Labels: bug

#112 Feature/llm dispatch mqtt produce
  pyproject.toml
  src/autopatchdatatypes/autopatchdatatypes/__init__.py
  src/autopatchdatatypes/autopatchdatatypes/patch_response.py
  src/autopatchdatatypes/autopatchdatatypes/transformer_metadata.py
  src/autopatchdatatypes/pyproject.toml
  src/autopatchpubsub/autopatchpubsub/message_broker_client.py
  src/autopatchpubsub/autopatchpubsub/test_message_broker_client.py
  src/autopatchpubsub/pyproject.toml
  src/autopatchshared/pyproject.toml
  src/code-property-graph-generator/Dockerfile
  src/code-property-graph-generator/code_property_graph_generator.py
  src/code-property-graph-generator/pyproject.toml
  src/code-property-graph-generator/requirements.txt
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/fuzzing_service.py
  src/fuzzing-service/pyproject.toml
  src/fuzzing-service/requirements.txt
  src/fuzzing-service/tests/test_fuzzing_service.py
  src/llm-dispatch-service/Dockerfile
  src/llm-dispatch-service/config/config.json
  src/llm-dispatch-service/config/dev-config.json
  src/llm-dispatch-service/config/dev-logging-config.json
  src/llm-dispatch-service/llm_dispatch_svc.py
  src/llm-dispatch-service/pyproject.toml
  src/llm-dispatch-service/requirements.txt
  src/llm-dispatch-service/test_llm_dispatch_service.py
  src/patch-evaluation-service/Dockerfile
  src/patch-evaluation-service/pyproject.toml
  src/patch-evaluation-service/requirements.txt
Labels: enhancement

#115 docs(readme diagram): use svg over png
  .github/workflows/build-and-push-docker-images.yml
  README.md
  docs/Diagrams/autopatch-devtools-v.0.6.1.drawio.svg
  docs/Diagrams/autopatch-v.0.6.1.drawio.png
Labels: documentation

#116 Docs/use svg for devtools diagram
  README.md
  docs/Diagrams/autopatch-devtools-v.0.6.1.drawio.png
  docs/Diagrams/autopatch-v.0.6.1.drawio.svg
Labels: documentation

#117 release(v0.7.0-alpha)
  docker-compose.yml
  src/autopatchdatatypes/autopatchdatatypes/patch_response.py
  src/code-property-graph-generator/config/config.json
  src/code-property-graph-generator/config/dev-config.json
  src/fuzzing-service/config/config.json
  src/fuzzing-service/config/dev-config.json
  src/patch-evaluation-service/config/config.json
  src/patch-evaluation-service/config/dev-config.json
Labels: enhancement

#118 Added CpgScanResult message consumption too llm dispatch service.
  src/code-property-graph-generator/code_property_graph_generator.py
  src/llm-dispatch-service/config/config.json
  src/llm-dispatch-service/config/dev-config.json
  src/llm-dispatch-service/llm_dispatch_svc.py
  src/llm-dispatch-service/llm_dispatch_svc_config.py
  src/llm-dispatch-service/test_llm_dispatch_service.py
Labels: enhancement

#114 Feature/update source compilation
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/test-coverage.yml
  .vscode/launch.json
  assets/input_codebase/CROMU_00007/Makefile
  assets/input_codebase/CROMU_00007/README.cgc.md
  assets/input_codebase/CROMU_00007/README.md
  assets/input_codebase/CROMU_00007/config.json
  assets/input_codebase/CROMU_00007/crash.input
  assets/input_codebase/CROMU_00007/include/timecard.h
  assets/input_codebase/CROMU_00007/pov/POV_00000.xml
  assets/input_codebase/CROMU_00007/pov/POV_00001.xml
  assets/input_codebase/CROMU_00007/pov/POV_00002.xml
  assets/input_codebase/CROMU_00007/sample.input
  assets/input_codebase/CROMU_00007/src/service.c
  assets/input_codebase/CROMU_00007/src/timecard.c
  assets/input_codebase/vulnerable.c
  assets/lily-demo-1/input/head.txt
  assets/lily-demo-1/input/u.txt
  pytest.ini
  src/autopatchpubsub/autopatchpubsub/test_message_broker_client.py
  src/autopatchshared/autopatchshared/__init__.py
  src/autopatchshared/autopatchshared/make_compile.py
  src/autopatchshared/autopatchshared/test_load_config_as_json.py
  src/autopatchshared/autopatchshared/test_make_compile.py
  src/autopatchshared/pyproject.toml
  src/code-property-graph-generator/Dockerfile
  src/code-property-graph-generator/code_property_graph_generator.py
  src/code-property-graph-generator/requirements.txt
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/config/config.json
  src/fuzzing-service/config/dev-config.json
  src/fuzzing-service/fuzz_svc_config.py
  src/fuzzing-service/fuzzing_service.py
  src/fuzzing-service/pytest.ini
  src/fuzzing-service/requirements.txt
  src/fuzzing-service/tests/test_fuzzing_service.py
  src/llm-dispatch-service/Dockerfile
  src/llm-dispatch-service/pytest.ini
  src/llm-dispatch-service/requirements.txt
  src/patch-evaluation-service/Dockerfile
  src/patch-evaluation-service/patch_evaluation_service.py
  src/patch-evaluation-service/pytest.ini
  src/patch-evaluation-service/requirements.txt
  src/patch-evaluation-service/test_patch_evaluation_service.py
Labels: enhancement

#120 feature/patch eval consume patch response strong type
  pyproject.toml
  src/autopatchpubsub/autopatchpubsub/message_broker_client.py
  src/autopatchpubsub/pyproject.toml
  src/code-property-graph-generator/Dockerfile
  src/code-property-graph-generator/requirements.txt
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/requirements.txt
  src/llm-dispatch-service/Dockerfile
  src/llm-dispatch-service/config/config.json
  src/llm-dispatch-service/config/dev-config.json
  src/llm-dispatch-service/llm_dispatch_svc.py
  src/llm-dispatch-service/requirements.txt
  src/patch-evaluation-service/Dockerfile
  src/patch-evaluation-service/config/config.json
  src/patch-evaluation-service/config/dev-config.json
  src/patch-evaluation-service/patch_eval_config.py
  src/patch-evaluation-service/patch_evaluation_service.py
  src/patch-evaluation-service/requirements.txt
  src/patch-evaluation-service/test_patch_evaluation_service.py
Labels: enhancement

#121 tests: add coverage gutters for test coverage viewing locally
  .devcontainer/devcontainer.json
Labels: enhancement

#123 feature/produce evaluated results data
  .devcontainer/devcontainer.json
  .flake8
  .github/linters/.flake8
  .vscode/extensions.json
  .vscode/launch.json
  assets/remove-all-docker-images.sh
  docker-compose.yml
  pyproject.toml
  src/autopatchdatatypes/autopatchdatatypes/patch_response_status.py
  src/autopatchdatatypes/pyproject.toml
  src/autopatchdatatypes/tests/test_crash_detail.py
  src/autopatchpubsub/archive/Dockerfile
  src/autopatchpubsub/archive/mqtt-produce-consume.py
  src/autopatchpubsub/autopatchpubsub/message_broker_client.py
  src/autopatchpubsub/pyproject.toml
  src/autopatchpubsub/tests/test_message_broker_client.py
  src/autopatchshared/tests/test_get_current_timestamp.py
  src/autopatchshared/tests/test_init_logging.py
  src/autopatchshared/tests/test_load_config_as_json.py
  src/autopatchshared/tests/test_make_compile.py
  src/code-property-graph-generator/Dockerfile
  src/code-property-graph-generator/config/config.json
  src/code-property-graph-generator/config/dev-config.json
  src/code-property-graph-generator/config/dev-logging-config.json
  src/code-property-graph-generator/config/logging-config.json
  src/code-property-graph-generator/pyproject.toml
  src/code-property-graph-generator/requirements.txt
  src/code-property-graph-generator/test_code_property_graph_generator.py
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/config/config.json
  src/fuzzing-service/config/dev-config.json
  src/fuzzing-service/config/logging-config.json
  src/fuzzing-service/fuzzing_service.py
  src/fuzzing-service/pyproject.toml
  src/fuzzing-service/requirements.txt
  src/fuzzing-service/test_fuzzing_service.py
  src/fuzzing-service/tests/__init__.py
  src/llm-dispatch-service/Dockerfile
  src/llm-dispatch-service/config/config.json
  src/llm-dispatch-service/config/dev-config.json
  src/llm-dispatch-service/config/logging-config.json
  src/llm-dispatch-service/data/prompts/old_user_prompt.txt
  src/llm-dispatch-service/data/prompts/system_prompt.txt
  src/llm-dispatch-service/data/prompts/user_prompt.txt
  src/llm-dispatch-service/llm_dispatch_svc.py
  src/llm-dispatch-service/llm_dispatch_svc_config.py
  src/llm-dispatch-service/pyproject.toml
  src/llm-dispatch-service/requirements.txt
  src/llm-dispatch-service/test_llm_dispatch_service.py
  src/patch-evaluation-service/Dockerfile
  src/patch-evaluation-service/config/config.json
  src/patch-evaluation-service/config/dev-config.json
  src/patch-evaluation-service/config/logging-config.json
  src/patch-evaluation-service/patch_eval_config.py
  src/patch-evaluation-service/patch_evaluation_service.py
  src/patch-evaluation-service/pyproject.toml
  src/patch-evaluation-service/requirements.txt
  src/patch-evaluation-service/test_patch_evaluation_service.py
Labels: enhancement

#126 docs(readme): update structured logging screenshot entry on front readme
  docs/images/structured-logging.png
Labels: documentation

#130 release(v0.9.0-beta): full CPG prompt context augmentation.
  README.md
  Taskfile.yml
  assets/notebooks/archive/CPGdemo.ipynb
  assets/notebooks/archive/run_joern-scan_results.ipynb
  assets/notebooks/data_analysis.ipynb
  docker-compose.yml
  pyproject.toml
  src/autopatchdatatypes/README.md
  src/autopatchdatatypes/pyproject.toml
  src/autopatchpubsub/README.md
  src/autopatchpubsub/pyproject.toml
  src/autopatchshared/README.md
  src/autopatchshared/pyproject.toml
  src/code-property-graph-generator/Dockerfile
  src/code-property-graph-generator/README.md
  src/code-property-graph-generator/pyproject.toml
  src/code-property-graph-generator/requirements.txt
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/README.md
  src/fuzzing-service/pyproject.toml
  src/fuzzing-service/requirements.txt
  src/llm-dispatch-service/Dockerfile
  src/llm-dispatch-service/README.md
  src/llm-dispatch-service/pyproject.toml
  src/llm-dispatch-service/requirements.txt
  src/patch-evaluation-service/Dockerfile
  src/patch-evaluation-service/README.md
  src/patch-evaluation-service/config/config.json
  src/patch-evaluation-service/config/dev-config.json
  src/patch-evaluation-service/pyproject.toml
  src/patch-evaluation-service/requirements.txt
Labels: documentation, enhancement
