Repository sysec-uic/AutoPatch-LLM, pull requests merged in 2025-02, with the labels that each got.

#15 update README with logging section
  README.md
  docs/images/afl_buglog_vulnerable_log_example.jpeg
  docs/images/command_log_vulnerable_log.jpeg
Labels: documentation

#13 feautre/pull-request-template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#9 Docs/demo
  docs/AFLTroubleshooting.md
  docs/QuickStart.md
  docs/afl_troubleshooting.txt
Labels: documentation

#19 add new python file to demo pr template:
  new-file.py
Labels: documentation

#21 docs/glossary
  README.md
Labels: documentation

#29 Feature #30 Add First Github Action - Super Linter
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/super-linter.yml
  README.md
  pyproject.toml
  src/.env.example
  src/Dockerfile
  src/README.md
  src/fuzzing-service/.env.example
  src/fuzzing-service/Dockerfile
  src/fuzzing-service/README.md
  src/fuzzing-service/data/README.md
  src/fuzzing-service/log/README.md
  src/llm-dispatch/invoke-chatgpt-API-hello-world-2.py
  src/llm-dispatch/invoke-chatgpt-API-hello-world.py
Labels: enhancement

#28 #8 docs/fuzzing-component-adr "Add ADR for standalone fuzzing component"
  assets/ArchitecturalDecisionRecords/adr-independent-fuzzing-component.md
  assets/ArchitecturalDecisionRecords/template-adr.md
  assets/TechnicalSpikes/template-technical-spike.md
Labels: documentation

#35 update README with table of contents. update ADRs to be versioned in…
  README.md
  assets/ArchitecturalDecisionRecords/000.template-adr.md
  assets/ArchitecturalDecisionRecords/002.adr-config-format.md
  assets/ArchitecturalDecisionRecords/003.adr-independent-fuzzing-component.md
  assets/TechnicalSpikes/000.template-technical-spike.md
Labels: documentation

#36 Enable flake8
  .flake8
  .github/linters/.flake8
  .github/workflows/super-linter.yml
  src/main.py
Labels: enhancement

#38 docs(ADR): Add CloudEvent specification ADR
  .github/PULL_REQUEST_TEMPLATE.md
  docs/ArchitecturalDecisionRecords/000.template-adr.md
  docs/ArchitecturalDecisionRecords/002.adr-config-format.md
  docs/ArchitecturalDecisionRecords/003.adr-independent-fuzzing-component.md
  docs/ArchitecturalDecisionRecords/004.adr-cloudevents.md
  docs/ArchitecturalDecisionRecords/adr-config-format.md
  docs/TechnicalSpikes/000.template-technical-spike.md
Labels: documentation, Architectural Decision Record

#39 Engineering Fundamentals: Add Issue Templates
  .github/ISSUE_TEMPLATE/✨-feature-request.md
  .github/ISSUE_TEMPLATE/🐞-bug-report.md
  .github/ISSUE_TEMPLATE/📌-task.md
Labels: enhancement

#32 CONTRIBUTING.md change
  CONTRIBUTING.md
Labels: documentation

#37 feature/crashdetaildatatype
  .devcontainer/devcontainer.env.example
  .devcontainer/devcontainer.json
  .github/workflows/build-datatypes-package.yml
  .github/workflows/super-linter.yml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  README.md
  docker-compose.yml
  docs/AFLTroubleshooting.md
  docs/images/afl_buglog_vulnerable_log_example.jpeg
  docs/images/command_log_vulnerable_log.jpeg
  docs/images/structured-logging.png
  pyproject.toml
  src/autopatchdatatypes/README.md
  src/autopatchdatatypes/autopatchdatatypes/__init__.py
  src/autopatchdatatypes/autopatchdatatypes/crash_detail.py
  src/autopatchdatatypes/pyproject.toml
  src/dev-requirements.txt
  src/fuzzing-service/.gitignore
  src/fuzzing-service/Taskfile.yml
  src/fuzzing-service/bin/README.md
  src/fuzzing-service/config/dev-config.json
  src/fuzzing-service/config/logging-config.json
  src/fuzzing-service/fuzzing_service.py
  src/fuzzing-service/pyproject.toml
  src/fuzzing-service/requirements.txt
  src/fuzzing-service/test_fuzzing_service.py
Labels: enhancement

#40 docs(mqtt): add technical spike for machine-to-machine communication using MQTT
  CONTRIBUTING.md
  docs/ArchitecturalDecisionRecords/004.adr-cloudevents.md
  docs/TechnicalSpikes/001.mqtt-techincal-spike.md
  docs/images/compose-mqtt-example.png
  docs/images/mqtt-consumer-python.png
  docs/images/mqtt-publisher-python.png
Labels: documentation, TechnicalSpike

#41 docs/adr mosquitto
  docs/ArchitecturalDecisionRecords/005.machine-comminucation-with-mqtt.md
Labels: Architectural Decision Record
